### PR TITLE
Update grid_sheet_view.xml

### PR DESCRIPTION
**Pull request by TheFinestArtist**
Update titleview margin referenced by [Material Guideline](https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-behavior)

### CODE REVIEW

**Comment by markrietveld** [comment]
The material guidelines don't specify a title on grid sheets, and because of that, they also don't specify margins for the title in that case. I don't think this change makes the behavior closer to the spec.

The grid itself uses 24 dp outside margins. Using a different margin for the title would probably make it look worse. Maybe a comparison screenshot would convince me otherwise, but right now I don't think we should merge this

**Comment by hzsweers** [comment]
I agree. Can you post a screenshot?

**Comment by TheFinestArtist** [comment]
It is 16dp actually!
components_bottomsheets_specs3

**Comment by hzsweers** [comment]
Sorry I meant a screenshot of how it looks with your proposed change

**Comment by markrietveld** [comment]
@TheFinestArtist that is a list sheet, which has different dimensions than the grid sheet

**Comment by TheFinestArtist** [comment]
@markrietveld You are correct! But even with grid sheet, the left margin for title would be same as the left margin for title in list sheet.

**Pull request closed without merging**
