### PR TITLE
Image picker sheet

### LINKED ISSUE #44: ImagePickerSheet
A sheet that shows a grid of most recent images, and also has two containers for retrieving from the camera or system image picker call.

Default implementation of retrieving images from local (where the user provides some `getImage(Uri uri)` implementation) or otherwise implement a `provideImage(int position)` interface if they want to source their own content.

### PR DESCRIPTION
**Pull request by hzsweers**
Resolves #44 

Screenrecord:
https://www.dropbox.com/s/e3s7yogil2c5t0x/Telecine_2015-08-23-23-07-25.mp4?dl=0

victara_tmolpe23 32-21 3hsweers08232015230814

### CODE REVIEW

**Comment by hzsweers** [comment]
@markrietveld can you review this?

**Comment by markrietveld** [comment]
Done reviewing up to here

**Comment by hzsweers** [comment]
@markrietveld updated

**Comment by hzsweers** [comment]
@markrietveld can I merge this?

**Comment by markrietveld** [comment]
Go for it

**Pull request merged**
