### PR TITLE
RecyclerView support in MenuSheetView

### PR DESCRIPTION
**Pull request by AKiniyalocts**
This adds support for RecyclerView in the bottom sheet for our MenuSheetView. I've included a `WrapLinearLayoutManager` to fix the wrap_content issue for a `LinearLayoutManager`. GridLayoutManager currently <strong>does not</strong> wrap content (fills the entire screen).

I've added an additional constructor for our `MenuSheetView` constructor, allowing you to pass in a `LayoutManager` for your recycler. I've also added two new `MenuType's`: `RECYCLER_LIST` and `RECYCLER_GRID`, which are also required in the `MenuSheetView` constructor when using a recycler.

### CODE REVIEW

**Comment by hzsweers** [comment]
Awesome, planning to take a look this weekend probably

**Comment by AKiniyalocts** [comment]
Cool beans. And already signed :+1:

**Comment by hzsweers** [comment]
So haven't gone through the code yet, but a couple things I wanted to touch on to see if you had plans/feedback for:

* I noticed this is only for SheetMenuView. We'd ideally like to have it for all the commons views.
* I think we'd want to pull the trigger on just one or the other, and not supporting both AbsListView and RecyclerView

Did you have plans regarding/thoughts for either of those?

**Comment by AKiniyalocts** [comment]
Good questions. And sorry for the late response.

<li>I figured I should implement this once (SheetMenuView in this instance) and then see if we want to follow the same pattern on the other commons views.</li>
<li>As for AbsListView, I did not want to lose any functionality we had in the original version (wrap_content on GridView), or break current users code.Then, once we get all of those features implemented, we'd pull the plug on AbsListView.</li>

**Comment by hzsweers** [comment]
Sorry about the delay, I've been on vacation. I've used the gridlayoutmanager implementation, and satisfied with its performance. Let's go full recyclerview, and pull out the AbsListView implementations.

Let me know if you have time, if not I can take care of this myself and use your code here as a template to go off of. There's a few other things we'd need (item decoration for grid spacing for instance), but I feel good about this implementation.

If you do decide to do it, let's clean up this PR as well. There are some merge conflicts that carried over between commits, and we'd like to keep all commits buildable.

**Comment by hzsweers** [comment]
Going to close this for now. Google plans to add wrap_content support in the future, so we can revisit then.

**Pull request closed without merging**
