### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by pavlospt**
### Context

We are still using this library and recently migrated to AndroidX. It seems though the Jetifier is not handling correctly some parts leading to a crash. 

```
Field 'androidx.fragment.app.Fragment.mContainerId' is inaccessible to class 'androidx.core.app.AccessFragmentInternals' (declaration of 'androidx.core.app.AccessFragmentInternals' appears in base.apk)
       at androidx.core.app.AccessFragmentInternals.getContainerId(AccessFragmentInternals.java:9)
```

### Contents of the PR

* Upgrade Gradle version to 5.2.1
* Upgrade AGP version to 3.4.0-rc01
* Upgrade compileSdkVersion to 28
* Upgrade appCompat dependency to version 28.0.0
* Upgrade supportv4 dependency to version 28.0.0
* Upgrade Glide to version 4.9.0
* Upgrade Novoda bintray-release plugin to version 0.9
* Update travis.yml to use android-28 version
* Update Glide call sites for the new usage
* Migrate project to AndroidX, using Android Studio migrator

It would be great if this PR could be merged in or at least a new branch is created in order to allow any users with AndroidX use it as well!

### CODE REVIEW

**Comment by sincerelamb** [comment]
how to solve the problem 
 'Field 'androidx.fragment.app.Fragment.mContainerId' is inaccessible to class 'androidx.core.app.AccessFragmentInternals' (declaration of 'androidx.core.app.AccessFragmentInternals' appears in base.apk)
       at androidx.core.app.AccessFragmentInternals.getContainerId(AccessFragmentInternals.java:9)'
I just got stuck there

**Comment by pavlospt** [comment]
You can use the versions available here: https://dl.bintray.com/pavlospt/android-libraries/com/github/pavlospt/

**Comment by sincerelamb** [comment]
I solved it just now...
Key point is the Package Name........ Thank you a lot

**Comment by ebbyferguson** [comment]
If you solved the issue, it would be helpful to just post the solution here.

**Comment by IamFive** [comment]
Hello, is there any problems with this PR and if not when will this PR being merged?

**Comment by IamFive** [comment]
@pavlospt it seems this repo is not active now(it's common for company opensource repo). Do u mind that i fork your repo and update the group id then upload it to maven center?

**Comment by pavlospt** [comment]
@IamFive I have already uploaded my migrated repo to Maven!

**Comment by IamFive** [comment]
> I have already uploaded my migrated repo to Maven

@pavlospt  I found the dependency is in your personal repo. May u upload it to maven center or jcenter. Personal repo is not allowed to import in my work ENV.

**Comment by pavlospt** [comment]
@IamFive ok I will update it and release a new version to Maven Central. In the meantime you can just use it from JCenter.

**Comment by bironader** [comment]
I am facing the same problem here after migrating to androidx how can I solve it ?? it seems it's not maintainable anymore

**Comment by hamedtayeban** [comment]
#2ADPT-CWS

**Comment by jupitar** [comment]
> You can use the versions available here: https://dl.bintray.com/pavlospt/android-libraries/com/github/pavlospt/

**Comment by jupitar** [comment]
关于androidx问题，可以这样使用，在仓库里面添加下面的仓库地址
   maven {
            credentials {
                username '62c42c1ca908b6a4db648e45'
                password 'KX7UFMN)u0-a'
            }
            url 'https://packages.aliyun.com/maven/repository/2249623-release-Xolwdg/'
        }
        maven {
            credentials {
                username '62c42c1ca908b6a4db648e45'
                password 'KX7UFMN)u0-a'
            }
            url 'https://packages.aliyun.com/maven/repository/2249623-snapshot-eBV8de/'
        }
引用方式：   compile 'com.flipboard:bottomsheet:1.5.3' 引用一个即可。不需要按照文档上面引用两个库。框架使用方式按不变

**Pull request closed without merging**
