### PR TITLE
Switch API to support composite listeners

### LINKED ISSUE #75: Proposal: Switch stateChangeListener to accept multiple listeners
Been thinking there might be some use cases where one would want to add multiple, such as coloring the status bar when it's expanded.

### PR DESCRIPTION
**Pull request by hzsweers**
Resolves #75

### CODE REVIEW

**Comment by markrietveld** [comment]
Why did the Travis build on this?

**Comment by hzsweers** [comment]
I think @SamThompson set it up to build on PRs

**Comment by SamThompson** [comment]
Yes, I enabled it so we know if the PR builds successfully and aren't accidentally merging stuff that breaks the build. This verification can be done manually, but it's convenient for Travis to do it for us.

**Comment by SamThompson** [comment]
Ok, looks good.

**Pull request merged**
